import { motion, useReducedMotion } from 'framer-motion';
import { Area, AreaChart, Line, LineChart, ResponsiveContainer, Tooltip } from 'recharts';
import { Activity, ArrowRight, Bell, Bike, Bolt, CheckCircle2, ChevronRight, Clock3, Eye, GitCompare, Heart, MapPin, MessageCircle, PackagePlus, Phone, Search, ShieldCheck, Sparkles, Star, Trash2, TrendingDown, Trophy, UserRound, WalletCards, Wrench } from 'lucide-react';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import type { Listing, User, WantedRequest } from '../../types';
import { formatSom } from '../../utils/format';
import { listingImageUrl } from '../../utils/media';

const rise = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-60px' }, transition: { duration: .38 } };

export function LuxuryWidgetCard({ title, icon, to = '/market', loading, error, empty, children, className = '' }: { title: string; icon: ReactNode; to?: string; loading?: boolean; error?: string; empty?: boolean; children: ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.section {...(reduced ? {} : rise)} className={`luxury-card ${className}`}>
    <header className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="widget-icon">{icon}</span><h2 className="text-xl font-black uppercase tracking-tight sm:text-2xl">{title}</h2></div><Link to={to} className="widget-link">Смотреть все <ChevronRight size={15}/></Link></header>
    {loading ? <WidgetSkeleton/> : error ? <WidgetState icon={<Bolt/>} text={error}/> : empty ? <WidgetState icon={<Bike/>} text="Здесь пока ничего нет"/> : children}
  </motion.section>;
}

function WidgetSkeleton() { return <div className="grid gap-3"><div className="h-32 animate-pulse rounded-xl bg-white/[.05]"/><div className="h-4 w-2/3 animate-pulse rounded bg-white/[.05]"/></div>; }
function WidgetState({icon,text}:{icon:ReactNode;text:string}) { return <div className="grid min-h-36 place-items-center rounded-xl border border-dashed border-white/10 text-center text-white/40"><div>{icon}<p className="mt-2 text-sm">{text}</p></div></div>; }

export function AnimatedCounter({ value, suffix = '' }: { value: number; suffix?: string }) {
  const [shown, setShown] = useState(0); const reduced = useReducedMotion();
  useEffect(() => { if (reduced) { setShown(value); return; } let start = 0; const since = performance.now(); const tick = (now:number) => { const p = Math.min(1,(now-since)/700); setShown(Math.round(value*(1-Math.pow(1-p,3)))); if(p<1) start=requestAnimationFrame(tick); }; start=requestAnimationFrame(tick); return()=>cancelAnimationFrame(start); },[value,reduced]);
  return <>{shown.toLocaleString('ru-KG')}{suffix}</>;
}

const ListingMini = ({ item, rank }: { item: Listing; rank?: number }) => <Link to={`/listing/${item.id}`} className="group relative min-w-[250px] overflow-hidden rounded-2xl border border-white/10 bg-black/40 transition duration-300 hover:-translate-y-1 hover:border-acid/40 sm:min-w-[290px]">
  <div className="relative h-40 overflow-hidden"><img src={listingImageUrl(item.images?.[0]?.image_url)} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" alt=""/><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent"/>{rank && <span className="absolute left-3 top-3 rounded-full bg-acid px-2 py-1 text-xs font-black text-black">#{rank}</span>}</div>
  <div className="space-y-3 p-4"><div className="line-clamp-1 font-black uppercase">{item.title}</div><div className="text-2xl font-black text-acid transition group-hover:[text-shadow:0_0_18px_rgba(182,255,0,.4)]">{formatSom(item.price)}</div><div className="flex justify-between text-xs text-white/45"><span className="flex gap-1"><MapPin size={13}/>{item.city}</span><span className="flex gap-3"><b className="flex gap-1"><Eye size={13}/>{item.views || 0}</b><b className="flex gap-1"><Heart size={13}/>{Math.max(2,Math.round((item.views||8)/5))}</b></span></div><div className="flex gap-2 text-[10px] font-black uppercase">{item.is_urgent&&<span className="tag-red">Срочно</span>}{item.is_bargain&&<span className="tag">Торг</span>}{item.is_exchange&&<span className="tag">Обмен</span>}<span className="ml-auto flex gap-1 text-amber-300"><Star size={12} fill="currentColor"/>{Number(item.user?.rating||4.8).toFixed(1)}</span></div></div>
</Link>;

export function PopularListingsWidget({ listings, loading, error }: { listings: Listing[]; loading?: boolean; error?: string }) { return <LuxuryWidgetCard title="Популярные объявления" icon={<Trophy/>} loading={loading} error={error} empty={!loading&&!listings.length} className="xl:col-span-2"><div className="hide-scroll flex snap-x gap-4 overflow-x-auto pb-2">{[...listings].sort((a,b)=>b.views-a.views).slice(0,6).map((x,i)=><ListingMini key={x.id} item={x} rank={i+1}/>)}</div></LuxuryWidgetCard>; }

export function PriceHistoryWidget({ listing }: { listing?: Listing }) {
  const initial=listing?.initial_price||52000,current=listing?.price||41900, drop=Math.max(0,initial-current), percent=Math.round(drop/initial*100); const chart=[initial,initial-1200,current+2800,current].map((price,i)=>({i,price}));
  return <LuxuryWidgetCard title="Цена снижена" icon={<TrendingDown/>} empty={!listing}><div className="grid gap-5 sm:grid-cols-2"><div><span className="pulse-soft inline-flex rounded-full bg-danger/15 px-3 py-1 text-xs font-black uppercase text-danger">Цена снижена</span><div className="mt-4 text-lg text-white/35 line-through">{formatSom(initial)}</div><div className="text-4xl font-black text-white">{formatSom(current)}</div><div className="mt-3 flex items-center gap-3"><b className="text-2xl text-danger">−<AnimatedCounter value={percent}/>%</b><span className="text-sm text-white/50">Экономия<br/><b className="text-white">{formatSom(drop)}</b></span></div><p className="mt-3 text-xs text-white/35">Изменено {new Date(listing?.last_price_change_at||Date.now()).toLocaleDateString('ru-KG')}</p></div><ResponsiveContainer width="100%" height={150}><AreaChart data={chart}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b6ff00" stopOpacity={.3}/><stop offset="1" stopColor="#b6ff00" stopOpacity={0}/></linearGradient></defs><Area dataKey="price" stroke="#b6ff00" strokeWidth={2} fill="url(#priceFill)" isAnimationActive/></AreaChart></ResponsiveContainer></div></LuxuryWidgetCard>;
}

export function UrgentListingsWidget({ listings }: { listings: Listing[] }) { const items=listings.filter(x=>x.is_urgent).slice(0,3); return <LuxuryWidgetCard title="Срочные продажи" icon={<Bolt/>} empty={!items.length}><div className="space-y-3">{items.map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl border-l-2 border-danger bg-black/30 p-3"><span className="h-2 w-2 animate-pulse rounded-full bg-danger"/><img className="h-16 w-20 rounded-lg object-cover" src={listingImageUrl(x.images?.[0]?.image_url)}/><div className="min-w-0 flex-1"><Link to={`/listing/${x.id}`} className="line-clamp-1 font-black">{x.title}</Link><p className="text-xs text-white/40"><Clock3 size={12} className="inline"/> опубликовано {timeAgo(x.created_at)}</p><b className="text-acid">{formatSom(x.price)}</b></div><div className="grid gap-1"><Link title="Написать" className="icon-button" to={`/listing/${x.id}`}><MessageCircle size={16}/></Link>{x.user?.contact&&<a title="Позвонить" className="icon-button" href={`tel:${x.user.contact}`}><Phone size={16}/></a>}</div></div>)}</div></LuxuryWidgetCard>; }

export function NearbyListingsWidget({ listings, city='Бишкек' }: { listings: Listing[]; city?: string }) { const near=listings.filter(x=>x.city===city).slice(0,3); return <LuxuryWidgetCard title="Новые рядом" icon={<MapPin/>} empty={!near.length}><div className="mini-map mb-4"><MapPin className="text-acid"/><span>{city} · радиус 12 км</span></div><div className="grid gap-3">{near.map((x,i)=><Link key={x.id} to={`/listing/${x.id}`} className="flex items-center gap-3 rounded-xl bg-white/[.025] p-2 hover:bg-white/[.05]"><img src={listingImageUrl(x.images?.[0]?.image_url)} className="h-14 w-16 rounded-lg object-cover"/><div className="min-w-0 flex-1"><b className="line-clamp-1">{x.title}</b><span className="text-xs text-white/40">{i*2+1} км · {timeAgo(x.created_at)}</span></div><b className="text-acid">{formatSom(x.price)}</b></Link>)}</div></LuxuryWidgetCard>; }

export function BikeFinderWidget({ listings }: { listings: Listing[] }) { const [step,setStep]=useState(0); const [type,setType]=useState('MTB'); const steps=['Рост и бюджет','Стиль катания','Город и состояние']; return <LuxuryWidgetCard title="Подбор велосипеда" icon={<Search/>}><div className="mb-5 h-1 rounded bg-white/10"><motion.div className="h-full rounded bg-acid" animate={{width:`${(step+1)/3*100}%`}}/></div><p className="text-xs font-black uppercase text-white/35">Шаг {step+1}/3 · {steps[step]}</p><div className="mt-4 grid grid-cols-2 gap-2">{step===0?<><input className="premium-input" placeholder="Рост, см"/><input className="premium-input" placeholder="Бюджет, сом"/></>:step===1?['MTB','Road','Fixed','City'].map(x=><button onClick={()=>setType(x)} className={`choice ${type===x?'choice-active':''}`}>{x}</button>):<><input className="premium-input" placeholder="Город"/><select className="premium-input"><option>Любое состояние</option><option>Новое</option><option>Б/у</option></select></>}</div><button className="premium-action mt-4 w-full" onClick={()=>setStep((step+1)%3)}>{step===2?`Найдено вариантов: ${listings.length}`:'Продолжить'} <ArrowRight size={17}/></button></LuxuryWidgetCard>; }

const parts=[['Рама',18000],['Вилка',8500],['Колёса',14000],['Руль',3200],['Система',7500],['Седло',2800],['Педали',1900]] as const;
export function DreamBuildWidget(){const [selected,setSelected]=useState<number[]>([0]); const total=selected.reduce((s,i)=>s+parts[i][1],0); return <LuxuryWidgetCard title="Сборка мечты" icon={<Wrench/>} to="/market"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{parts.map(([name,price],i)=><motion.button whileTap={{scale:.96}} key={name} onClick={()=>setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])} className={`choice text-left ${selected.includes(i)?'choice-active':''}`}><PackagePlus size={17}/><b>{name}</b><small>{formatSom(price)}</small></motion.button>)}</div><div className="mt-5 flex items-end justify-between border-t border-white/10 pt-4"><div><span className="text-xs uppercase text-white/35">{selected.length}/7 элементов · ≈ {(selected.length*1.3).toFixed(1)} кг</span><div className="text-3xl font-black"><AnimatedCounter value={total}/> сом</div></div><CheckCircle2 className="text-acid"/></div></LuxuryWidgetCard>}

const spark=[3,6,5,9,8,12,15].map((v,i)=>({i,v}));
export function ActivityStatsWidget(){const stats=[['Новых сегодня',24],['Продавцов',318],['Продано',86],['Онлайн',142],['Сообщений',619]];return <LuxuryWidgetCard title="Активность VELOHAM" icon={<Activity/>} className="xl:col-span-2"><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{stats.map(([name,val])=><div className="stat-tile" key={name}><b><AnimatedCounter value={Number(val)}/></b><span>{name}</span><ResponsiveContainer width="100%" height={34}><LineChart data={spark}><Line dataKey="v" stroke="#b6ff00" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div>)}</div></LuxuryWidgetCard>}

export function TopSellersWidget({ users }: { users: User[] }) { const display=users.slice(0,3); return <LuxuryWidgetCard title="Лучшие продавцы" icon={<Trophy/>} empty={!display.length}>{<div className="grid gap-3">{display.map((u,i)=><Link to={`/profile/${u.id}`} key={u.id} className={`seller-row ${i===0?'seller-gold':''}`}><div className="avatar">{u.avatar_url?<img src={u.avatar_url}/>:u.username?.[0]}</div><div className="min-w-0 flex-1"><b>{u.username}</b><p className="text-xs text-white/40">Ответ ≈ 12 мин · с {new Date(u.created_at).getFullYear()}</p></div><span className="flex gap-1 text-amber-300"><Star size={14} fill="currentColor"/>{Number(u.rating||4.8).toFixed(1)}</span><ShieldCheck size={18} className="text-acid"/></Link>)}</div>}</LuxuryWidgetCard>; }

export function NotificationsWidget(){return <LuxuryWidgetCard title="Уведомления" icon={<Bell/>} to="/profile"><div className="space-y-2">{[['Цена снижена','Cannondale CAAD13 теперь дешевле','2 мин'],['Новое сообщение','Азамат ответил по объявлению','8 мин'],['В избранном','Ваш велосипед сохранили 4 раза','1 ч']].map(([t,d,time],i)=><div className="notification-row" key={t}><span className={i===0?'bg-danger':'bg-acid'}/><div className="flex-1"><b>{t}</b><p>{d}</p></div><small>{time}</small></div>)}</div></LuxuryWidgetCard>}
export function RecentMessagesWidget(){return <LuxuryWidgetCard title="Последние сообщения" icon={<MessageCircle/>} to="/chats"><div className="space-y-2">{[['Азамат','Рама ещё в продаже?','2'],['Daniyar','Могу забрать сегодня','0']].map(([name,text,n])=><Link to="/chats" className="seller-row" key={name}><div className="avatar">{name[0]}</div><div className="flex-1"><b>{name}</b><p className="text-xs text-white/40">{text}</p></div>{n!=='0'&&<span className="unread">{n}</span>}</Link>)}</div></LuxuryWidgetCard>}
export function RecentlyViewedWidget({listings}:{listings:Listing[]}){const [items,setItems]=useState(listings.slice(0,4));return <LuxuryWidgetCard title="Недавно просмотренные" icon={<Clock3/>} empty={!items.length} className="xl:col-span-2"><div className="hide-scroll flex gap-3 overflow-auto">{items.map(x=><div className="relative" key={x.id}><ListingMini item={x}/><button className="absolute right-2 top-2 rounded-full bg-black/70 p-2" onClick={()=>setItems(v=>v.filter(i=>i.id!==x.id))}><Trash2 size={14}/></button></div>)}</div><button className="mt-3 text-xs font-black uppercase text-white/35 hover:text-danger" onClick={()=>setItems([])}>Очистить историю</button></LuxuryWidgetCard>}
export function BuyerRequestsWidget({requests=[]}:{requests?:WantedRequest[]}){return <LuxuryWidgetCard title="Хочу купить" icon={<WalletCards/>} to="/wanted" empty={!requests.length}><div className="space-y-3">{requests.slice(0,3).map(x=><div className="rounded-xl border border-white/10 p-3" key={x.id}><div className="flex justify-between"><b>{x.title}</b><small>{x.city}</small></div><p className="mt-1 text-sm text-white/45">{x.preferred_bike_type||x.category} · {x.status}</p><b className="text-acid">{formatSom(x.min_budget)}—{formatSom(x.max_budget)}</b><div className="mt-3 flex gap-2"><Link to={`/wanted/${x.id}`} className="mini-action">Предложить</Link><Link to={`/wanted/${x.id}`} className="mini-action">Написать</Link></div></div>)}</div></LuxuryWidgetCard>}
export function CompareListingsWidget({listings}:{listings:Listing[]}){const [chosen,setChosen]=useState(listings.slice(0,2));return <LuxuryWidgetCard title="Сравнение" icon={<GitCompare/>} empty={!chosen.length}><div className="grid grid-cols-2 gap-2">{chosen.map(x=><div className="rounded-xl bg-black/30 p-3" key={x.id}><img className="h-20 w-full rounded-lg object-cover" src={listingImageUrl(x.images?.[0]?.image_url)}/><b className="mt-2 block line-clamp-1">{x.title}</b><strong className="text-acid">{formatSom(x.price)}</strong><p className="text-xs text-white/40">{x.condition} · {x.frame_size||'размер не указан'}</p></div>)}</div><button className="premium-action mt-3 w-full" onClick={()=>setChosen(listings.slice(0,3))}>Сравнить до трёх</button></LuxuryWidgetCard>}
export function ProfileProgressWidget({user}:{user?:User|null}){const progress=user?72:0;return <LuxuryWidgetCard title="Ваш профиль" icon={<UserRound/>} to={user?'/profile':'/login'} empty={!user}><div className="flex items-center gap-5"><div className="relative grid h-24 w-24 place-items-center rounded-full" style={{background:`conic-gradient(#b6ff00 ${progress}%,rgba(255,255,255,.08) 0)`}}><div className="grid h-20 w-20 place-items-center rounded-full bg-[#111]"><b>{progress}%</b></div></div><div><h3 className="text-2xl font-black">{user?.username}</h3><p className="text-sm text-white/40">Рейтинг {Number(user?.rating||0).toFixed(1)} · 4 объявления</p><b className="mt-2 block text-acid">1 240 VELO-бонусов</b></div></div></LuxuryWidgetCard>}

function timeAgo(date:string){const h=Math.max(1,Math.floor((Date.now()-new Date(date).getTime())/3600000));return h<24?`${h} ч назад`:`${Math.floor(h/24)} дн назад`;}
